KMeans Clustering

In [ ]:
import random
import math
import json
import sys
import time
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


This is the pseudocode tolad Load data from file and save in the numpy matrix.
You can use panda to read the dataset in to numpy matrix. data matrix will have data points. First column is point index. Rest of the columns have features.  ClassLabel has the labels.

In [ ]:
def load(file_name):
    # data(2D list or list of list): [[ . . .4 dimensions . . .], [..., ...], ...]
    x =  pd.read_csv(file_name).to_numpy()
    data = x[:,:-1]
    # classLabel = x[:,-1]
    return data   #classLabel contains class label

simple centroid initialization function

In [ ]:
def initialize_centroids_simple(data, dimension, k):
    #centroids: [[centroid0:  3 dimensions, , , ]; [centroid1: 3 dimensions ] ... ..]
    centroids = np.array([[0 for _ in range(dimension)] for _ in range(k)])
    #TO DO
    np.random.shuffle(data)
    rows = data[:k, :]
    centroids = rows
    #Write your code to return initialized centroids by randomly assiging them to K points
    return centroids

Calculate eucledian distance

In [ ]:
def get_euclidean_distance(p1, p2):
    distance = -1.0
    distance = np.linalg.norm(p1 - p2)
    return distance

KMeans Function


In [ ]:
def kmeans(data, dimension, k):
    N = np.size(data, 0)
    #centroids: [[centroid0:  , , ,3 dimensions, , , ]; [centroid1: , , ,3 dimensions, , , ] ... ..]
    centroids = initialize_centroids_simple(data, dimension, k)
    #cluster_affiliation: cluster_affiliation = [clusternumber, clutsernumber, ..., ..., ..., ...]
    flag = 1
    #initialize the cluster affiliations. Initially assign -1
    cluster_affiliation = np.array([-1 for _ in range(0, N)])
    while flag:
       for i, point in enumerate(data):
            min_distance = float('inf')
            min_distance_index = None

            #find closest centroids for each data points
            for cluster_index, centroid in enumerate(centroids): #use numpy equivalent code
                distance = get_euclidean_distance(centroid, point)
                if distance < min_distance:
                    min_distance = distance
                    min_distance_index = cluster_index

            #record or update cluster for each data points
            if cluster_affiliation[i] != min_distance_index:
               cluster_affiliation[i] = min_distance_index

       #recompute centroids
       new_centroids = np.array([[0 for _ in range(dimension)] for _ in range(k)]) # new centroids initialized with 0
       cluster_point_count = np.array([0 for _ in range(k)]) #keep number of points for each cluster. You should use
       #cluster_affiliation  to calculate it
       #TO DO
       #write your code to count each cluster pointcount and store them in clutser_point_count structure
       cluster_array = [[] for _ in range(k)]
       for i in range(N):   # make saparation by diff cluster
         cluster_point_count[cluster_affiliation[i]] += 1
         cluster_array[cluster_affiliation[i]].append(data[i])

       #recompute centroids using the count
       for i in range(len(cluster_array)):    # update it's centroids
         new_centroids[i] = np.divide(np.sum(cluster_array[i], axis = 0),cluster_point_count[i])

       for i in range(k):
         if get_euclidean_distance(new_centroids[i],centroids[i])<0.00005:
           flag  = False

       centroids = new_centroids

    #TO DO
    #Terminate the while loop based on termination criteria. Write your code to turn flag = false
    return (centroids, cluster_affiliation)


Driver funtion/Main Function

In [ ]:
def main():


  K = 4
  data = load('/content/drive/MyDrive/data set/wheetseeds.csv')
  dimension = np.size(data, 1)

  centroids, cluster_affiliation = kmeans(data, dimension, K)
  # print('Duration: %s' % (time.time() - start))

  print(centroids, cluster_affiliation)



main()





[[18 16  0  6  3  3  5]
 [14 14  0  5  3  2  5]
 [12 13  0  5  2  4  5]
 [11 13  0  5  2  5  5]] [0 1 2 3 1 0 0 0 0 2 3 2 1 0 0 0 1 3 2 2 2 1 0 2 1 0 1 0 1 1 0 3 2 3 0 0 2
 2 2 0 1 2 3 2 0 1 0 2 0 3 0 0 2 0 1 1 2 2 0 3 2 2 0 1 1 2 1 0 3 1 1 0 3 3
 1 0 1 1 0 0 2 2 0 1 1 3 0 2 2 0 0 2 1 0 0 1 2 2 0 2 0 0 0 1 1 2 3 1 0 1 1
 1 2 2 0 2 3 2 2 1 1 2 1 1 1 3 2 2 1 1 1 0 2 1 0 0 2 2 0 2 1 0 0 0 2 2 1 3
 1 3 0 0 2 3 1 0 0 0 0 0 2 1 1 0 1 3 2 1 2 0 1 1 0 0 0 1 0 0 2 1 2 0 1 2 0
 1 2 1 1 0 3 1 0 1 0 0 1 0 0 0 0 1 1 2 0 2 2 0 1 3]
